 const regionsCountries = {
    "regions": [{
        "region_id": "1",
        "region_name": "APAC",
        "checked":true,
        "countries": [{
            "country_id": "1",
            "country_code": "AS",
            "country_name": "American Samoa",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "2",
            "country_code": "AU",
            "country_name": "Australia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "3",
            "country_code": "BN",
            "country_name": "Brunei",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "12",
            "country_code": "KH",
            "country_name": "Cambodia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "5",
            "country_code": "CN",
            "country_name": "China",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "4",
            "country_code": "CK",
            "country_name": "Cook Islands",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "33",
            "country_code": "TL",
            "country_name": "East Timor",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "6",
            "country_code": "FJ",
            "country_name": "Fiji",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "26",
            "country_code": "PF",
            "country_name": "French Polynesia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "8",
            "country_code": "GU",
            "country_name": "Guam",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "9",
            "country_code": "HK",
            "country_name": "Hong Kong",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "10",
            "country_code": "ID",
            "country_name": "Indonesia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "11",
            "country_code": "JP",
            "country_name": "Japan",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "13",
            "country_code": "KI",
            "country_name": "Kiribati",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "15",
            "country_code": "LA",
            "country_name": "Laos",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "19",
            "country_code": "MO",
            "country_name": "Macau",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "21",
            "country_code": "MY",
            "country_name": "Malaysia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "16",
            "country_code": "MH",
            "country_name": "Marshall Islands",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "7",
            "country_code": "FM",
            "country_name": "Micronesia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "18",
            "country_code": "MN",
            "country_name": "Mongolia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "17",
            "country_code": "MM",
            "country_name": "Myanmar",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "23",
            "country_code": "NR",
            "country_name": "Nauru",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "22",
            "country_code": "NC",
            "country_name": "New Caledonia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "25",
            "country_code": "NZ",
            "country_name": "New Zealand",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "24",
            "country_code": "NU",
            "country_name": "Niue",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "20",
            "country_code": "MP",
            "country_name": "Northern Mariana Islands",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "29",
            "country_code": "PW",
            "country_name": "Palau",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "27",
            "country_code": "PG",
            "country_name": "Papua New Guinea",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "28",
            "country_code": "PH",
            "country_name": "Philippines",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "39",
            "country_code": "WS",
            "country_name": "Samoa",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "31",
            "country_code": "SG",
            "country_name": "Singapore",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "30",
            "country_code": "SB",
            "country_name": "Solomon Islands",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "14",
            "country_code": "KR",
            "country_name": "South Korea",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "36",
            "country_code": "TW",
            "country_name": "Taiwan",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "32",
            "country_code": "TH",
            "country_name": "Thailand",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "34",
            "country_code": "TO",
            "country_name": "Tonga",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "35",
            "country_code": "TV",
            "country_name": "Tuvalu",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "38",
            "country_code": "VU",
            "country_name": "Vanuatu",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "37",
            "country_code": "VN",
            "country_name": "Vietnam",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }]
    }, {
        "region_id": "2",
        "region_name": "CA",
        "checked":true,
        "countries": [{
            "country_id": "1",
            "country_code": "CA",
            "country_name": "Canada",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }]
    }, {
        "region_id": "3",
        "region_name": "EU",
        "checked":true,
        "countries": [{
            "country_id": "2",
            "country_code": "AL",
            "country_name": "Albania",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "1",
            "country_code": "AD",
            "country_name": "Andorra",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "3",
            "country_code": "AM",
            "country_name": "Armenia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "4",
            "country_code": "AT",
            "country_name": "Austria",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "5",
            "country_code": "AZ",
            "country_name": "Azerbaijan",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "9",
            "country_code": "BY",
            "country_name": "Belarus",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "7",
            "country_code": "BE",
            "country_name": "Belgium",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "6",
            "country_code": "BA",
            "country_name": "Bosnia-Herzegovina",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "8",
            "country_code": "BG",
            "country_name": "Bulgaria",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "24",
            "country_code": "HR",
            "country_name": "Croatia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "11",
            "country_code": "CZ",
            "country_name": "Czech Republic",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "13",
            "country_code": "DK",
            "country_name": "Denmark",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "14",
            "country_code": "EE",
            "country_name": "Estonia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "17",
            "country_code": "FO",
            "country_name": "Faroe Islands",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "16",
            "country_code": "FI",
            "country_name": "Finland",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "18",
            "country_code": "FR",
            "country_name": "France",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "20",
            "country_code": "GE",
            "country_name": "Georgia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "12",
            "country_code": "DE",
            "country_name": "Germany",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "21",
            "country_code": "GI",
            "country_name": "Gibraltar",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "23",
            "country_code": "GR",
            "country_name": "Greece",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "22",
            "country_code": "GL",
            "country_name": "Greenland",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "25",
            "country_code": "HU",
            "country_name": "Hungary",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "28",
            "country_code": "IS",
            "country_name": "Iceland",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "26",
            "country_code": "IE",
            "country_name": "Ireland",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "27",
            "country_code": "IL",
            "country_name": "Israel",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "29",
            "country_code": "IT",
            "country_name": "Italy",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "33",
            "country_code": "LV",
            "country_name": "Latvia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "30",
            "country_code": "LI",
            "country_name": "Liechtenstein",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "31",
            "country_code": "LT",
            "country_name": "Lithuania",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "32",
            "country_code": "LU",
            "country_name": "Luxembourg",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "37",
            "country_code": "MK",
            "country_name": "Macedonia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "38",
            "country_code": "MT",
            "country_name": "Malta",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "35",
            "country_code": "MD",
            "country_name": "Moldova",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "34",
            "country_code": "MC",
            "country_name": "Monaco",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "36",
            "country_code": "ME",
            "country_name": "Montenegro",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "39",
            "country_code": "NL",
            "country_name": "Netherlands",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "40",
            "country_code": "NO",
            "country_name": "Norway",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "42",
            "country_code": "PS",
            "country_name": "Palestine Autonomous",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "41",
            "country_code": "PL",
            "country_name": "Poland",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "43",
            "country_code": "PT",
            "country_name": "Portugal",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "44",
            "country_code": "RO",
            "country_name": "Romania",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "46",
            "country_code": "RU",
            "country_name": "Russia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "45",
            "country_code": "RS",
            "country_name": "Serbia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "49",
            "country_code": "SK",
            "country_name": "Slovak Republic",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "48",
            "country_code": "SI",
            "country_name": "Slovenia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "15",
            "country_code": "ES",
            "country_name": "Spain",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "47",
            "country_code": "SE",
            "country_name": "Sweden",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "10",
            "country_code": "CH",
            "country_name": "Switzerland",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "50",
            "country_code": "UA",
            "country_name": "Ukraine",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "19",
            "country_code": "GB",
            "country_name": "United Kingdom",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "51",
            "country_code": "VA",
            "country_name": "Vatican City",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "52",
            "country_code": "WF",
            "country_name": "Wallis and Futuna Islands",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }]
    }, {
        "region_id": "4",
        "region_name": "LAC",
        "checked":true,
        "countries": [{
            "country_id": "2",
            "country_code": "AI",
            "country_name": "Anguilla",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "1",
            "country_code": "AG",
            "country_name": "Antigua & Barbuda",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "4",
            "country_code": "AR",
            "country_name": "Argentina",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "5",
            "country_code": "AW",
            "country_name": "Aruba",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "11",
            "country_code": "BS",
            "country_name": "Bahamas",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "6",
            "country_code": "BB",
            "country_name": "Barbados",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "12",
            "country_code": "BZ",
            "country_name": "Belize",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "7",
            "country_code": "BM",
            "country_name": "Bermuda",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "8",
            "country_code": "BO",
            "country_name": "Bolivia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "9",
            "country_code": "BQ",
            "country_name": "Bonaire, St. Eustatius and Saba",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "10",
            "country_code": "BR",
            "country_name": "Brazil",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "48",
            "country_code": "VG",
            "country_name": "British Virgin Islands",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "29",
            "country_code": "KY",
            "country_name": "Cayman Islands",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "13",
            "country_code": "CL",
            "country_name": "Chile",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "14",
            "country_code": "CO",
            "country_name": "Colombia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "15",
            "country_code": "CR",
            "country_name": "Costa Rica",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "16",
            "country_code": "CW",
            "country_name": "Curacao",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "17",
            "country_code": "DM",
            "country_name": "Dominica",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "18",
            "country_code": "DO",
            "country_name": "Dominican Republic",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "19",
            "country_code": "EC",
            "country_name": "Ecuador",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "41",
            "country_code": "SV",
            "country_name": "El Salvador",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "21",
            "country_code": "GF",
            "country_name": "French Guiana",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "20",
            "country_code": "GD",
            "country_name": "Grenada",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "22",
            "country_code": "GP",
            "country_name": "Guadeloupe",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "23",
            "country_code": "GT",
            "country_name": "Guatemala",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "24",
            "country_code": "GY",
            "country_name": "Guyana",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "26",
            "country_code": "HT",
            "country_name": "Haiti",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "25",
            "country_code": "HN",
            "country_name": "Honduras",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "27",
            "country_code": "JM",
            "country_name": "Jamaica",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "32",
            "country_code": "MQ",
            "country_name": "Martinique",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "34",
            "country_code": "MX",
            "country_name": "Mexico",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "33",
            "country_code": "MS",
            "country_name": "Montserrat",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "3",
            "country_code": "AN",
            "country_name": "Netherlands Antilles",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "35",
            "country_code": "NI",
            "country_name": "Nicaragua",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "36",
            "country_code": "PA",
            "country_name": "Panama",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "39",
            "country_code": "PY",
            "country_name": "Paraguay",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "37",
            "country_code": "PE",
            "country_name": "Peru",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "38",
            "country_code": "PR",
            "country_name": "Puerto Rico",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "28",
            "country_code": "KN",
            "country_name": "St. Kitts and Nevis",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "30",
            "country_code": "LC",
            "country_name": "St. Lucia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "42",
            "country_code": "SX",
            "country_name": "St. Maarten",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "31",
            "country_code": "MF",
            "country_name": "St. Martin",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "46",
            "country_code": "VC",
            "country_name": "St. Vincent & the Grenadines",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "40",
            "country_code": "SR",
            "country_name": "Suriname",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "44",
            "country_code": "TT",
            "country_name": "Trinidad & Tobago",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "43",
            "country_code": "TC",
            "country_name": "Turks & Caicos Islands",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "49",
            "country_code": "VI",
            "country_name": "U.S. Virgin Islands",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "45",
            "country_code": "UY",
            "country_name": "Uruguay",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "47",
            "country_code": "VE",
            "country_name": "Venezuela",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }]
    }, {
        "region_id": "5",
        "region_name": "MEISA",
        "checked":true,
        "countries": [{
            "country_id": "2",
            "country_code": "AF",
            "country_name": "Afghanistan",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "19",
            "country_code": "DZ",
            "country_name": "Algeria",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "3",
            "country_code": "AO",
            "country_name": "Angola",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "6",
            "country_code": "BH",
            "country_name": "Bahrain",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "4",
            "country_code": "BD",
            "country_name": "Bangladesh",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "8",
            "country_code": "BJ",
            "country_name": "Benin",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "9",
            "country_code": "BT",
            "country_name": "Bhutan",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "10",
            "country_code": "BW",
            "country_name": "Botswana",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "5",
            "country_code": "BF",
            "country_name": "Burkina Faso",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "7",
            "country_code": "BI",
            "country_name": "Burundi",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "15",
            "country_code": "CM",
            "country_name": "Cameroon",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "16",
            "country_code": "CV",
            "country_name": "Cape Verde",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "12",
            "country_code": "CF",
            "country_name": "Central African Republic",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "67",
            "country_code": "TD",
            "country_name": "Chad",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "13",
            "country_code": "CG",
            "country_name": "Congo",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "17",
            "country_code": "CY",
            "country_name": "Cyprus",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "14",
            "country_code": "CI",
            "country_name": "Côte D'ivoire (Ivory Coast)",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "11",
            "country_code": "CD",
            "country_name": "Democratic Republic of Congo",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "18",
            "country_code": "DJ",
            "country_name": "Djibouti",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "20",
            "country_code": "EG",
            "country_name": "Egypt",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "27",
            "country_code": "GQ",
            "country_name": "Equatorial Guinea",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "21",
            "country_code": "ER",
            "country_name": "Eritrea",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "22",
            "country_code": "ET",
            "country_name": "Ethiopia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "23",
            "country_code": "GA",
            "country_name": "Gabon",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "25",
            "country_code": "GM",
            "country_name": "Gambia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "24",
            "country_code": "GH",
            "country_name": "Ghana",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "26",
            "country_code": "GN",
            "country_name": "Guinea",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "28",
            "country_code": "GW",
            "country_name": "Guinea-Bissau",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "29",
            "country_code": "IN",
            "country_name": "India",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "31",
            "country_code": "IR",
            "country_name": "Iran",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "30",
            "country_code": "IQ",
            "country_name": "Iraq",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "32",
            "country_code": "JO",
            "country_name": "Jordan",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "36",
            "country_code": "KZ",
            "country_name": "Kazakhstan",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "33",
            "country_code": "KE",
            "country_name": "Kenya",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "35",
            "country_code": "KW",
            "country_name": "Kuwait",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "34",
            "country_code": "KG",
            "country_name": "Kyrgyzstan",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "37",
            "country_code": "LB",
            "country_name": "Lebanon",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "40",
            "country_code": "LS",
            "country_name": "Lesotho",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "39",
            "country_code": "LR",
            "country_name": "Liberia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "41",
            "country_code": "LY",
            "country_name": "Libya",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "43",
            "country_code": "MG",
            "country_name": "Madagascar",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "48",
            "country_code": "MW",
            "country_name": "Malawi",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "47",
            "country_code": "MV",
            "country_name": "Maldives",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "44",
            "country_code": "ML",
            "country_name": "Mali",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "45",
            "country_code": "MR",
            "country_name": "Mauritania",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "46",
            "country_code": "MU",
            "country_name": "Mauritius",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "42",
            "country_code": "MA",
            "country_name": "Morocco",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "49",
            "country_code": "MZ",
            "country_name": "Mozambique",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "50",
            "country_code": "NA",
            "country_name": "Namibia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "53",
            "country_code": "NP",
            "country_name": "Nepal",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "51",
            "country_code": "NE",
            "country_name": "Niger",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "52",
            "country_code": "NG",
            "country_name": "Nigeria",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "54",
            "country_code": "OM",
            "country_name": "Oman",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "55",
            "country_code": "PK",
            "country_name": "Pakistan",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "56",
            "country_code": "QA",
            "country_name": "Qatar",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "57",
            "country_code": "RE",
            "country_name": "Reunion Island",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "58",
            "country_code": "RW",
            "country_name": "Rwanda",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "59",
            "country_code": "SA",
            "country_name": "Saudi Arabia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "63",
            "country_code": "SN",
            "country_name": "Senegal",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "60",
            "country_code": "SC",
            "country_name": "Seychelles",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "62",
            "country_code": "SL",
            "country_name": "Sierra Leone",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "64",
            "country_code": "SO",
            "country_name": "Somalia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "76",
            "country_code": "ZA",
            "country_name": "South Africa",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "38",
            "country_code": "LK",
            "country_name": "Sri Lanka",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "61",
            "country_code": "SD",
            "country_name": "Sudan",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "66",
            "country_code": "SZ",
            "country_name": "Swaziland",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "65",
            "country_code": "SY",
            "country_name": "Syria",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "72",
            "country_code": "TZ",
            "country_name": "Tanzania",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "68",
            "country_code": "TG",
            "country_name": "Togo",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "70",
            "country_code": "TN",
            "country_name": "Tunisia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "71",
            "country_code": "TR",
            "country_name": "Turkey",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "69",
            "country_code": "TM",
            "country_name": "Turkmenistan",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "73",
            "country_code": "UG",
            "country_name": "Uganda",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "1",
            "country_code": "AE",
            "country_name": "United Arab Emirates",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "74",
            "country_code": "UZ",
            "country_name": "Uzbekistan",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "75",
            "country_code": "YE",
            "country_name": "Yemen",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "77",
            "country_code": "ZM",
            "country_name": "Zambia",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }, {
            "country_id": "78",
            "country_code": "ZW",
            "country_name": "Zimbabwe",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }]
    }, {
        "region_id": "6",
        "region_name": "US",
        "checked":true,
        "countries": [{
            "country_id": "1",
            "country_code": "US",
            "country_name": "United States",
            "eff_timestamp": "2000-01-01",
            "exp_timestamp": "2025-12-31",
            "lastUpdate_ID": "f769547",
            "checked":true,
        }]
    }]
}

export default regionsCountries;